#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/library_loader.sh"
source "${SCRIPT_DIR}/../lib/check.sh"

cmd_check() {
    ptk_check "$@"
}
