#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/library_loader.sh"
source "${SCRIPT_DIR}/../lib/rename.sh"

cmd_rename() {
    ptk_rename "$@"
}
