# Plex Toolkit common defaults
PTK_LOG_DIR="./logs"
PTK_REPORT_DIR="./reports"
PTK_DRY_RUN=true
PTK_VERBOSE=false
PTK_COLOR=true

PTK_INVENTORY_CSV_REPORT="inventory.csv"
PTK_INVENTORY_JSON_REPORT="inventory.json"
PTK_INVENTORY_LOG="inventory.log"

PTK_AUDIT_TEXT_REPORT="audit.log"
PTK_AUDIT_JSON_REPORT="audit.json"

PTK_VIDEO_EXTENSIONS="mkv mp4 ts"
